export default defineEventHandler(() => {
  // Return all reference data needed for cabin crew sales
  return {
    // Product inventory
    inventory: [
      {
        id: 1,
        name: 'Wireless Headphones Premium',
        itemNumber: 'ITM-001',
        barcode: '1234567890123',
        price: 89.99,
        category: 'Electronics',
        stock: 15,
        image: 'https://placehold.co/400x300/0066CC/FFF?text=Headphones',
        description: 'High-quality wireless headphones with noise cancellation',
      },
      {
        id: 2,
        name: 'Travel Pillow Deluxe',
        itemNumber: 'ITM-002',
        barcode: '2345678901234',
        price: 24.99,
        category: 'Comfort',
        stock: 30,
        image: 'https://placehold.co/400x300/00AA66/FFF?text=Pillow',
        description: 'Memory foam travel pillow for maximum comfort',
      },
      {
        id: 3,
        name: 'Luxury Perfume',
        itemNumber: 'ITM-003',
        barcode: '3456789012345',
        price: 125.00,
        category: 'Fragrance',
        stock: 20,
        image: 'https://placehold.co/400x300/CC0066/FFF?text=Perfume',
        description: 'Designer fragrance for men and women',
        hasVariants: true,
        variants: [
          {
            size: '50ml',
            sku: 'ARX-50',
            barcode: '3456789012345',
            uom: 'ML',
            status: 'Active',
            price: 125.00,
            stock: 15,
          },
          {
            size: '100ml',
            sku: 'ARX-100',
            barcode: '3456789012346',
            uom: 'ML',
            status: 'Active',
            price: 199.99,
            stock: 8,
          },
          {
            size: '150ml',
            sku: 'ARX-150',
            barcode: '3456789012347',
            uom: 'ML',
            status: 'Active',
            price: 275.00,
            stock: 5,
          },
        ],
      },
      {
        id: 4,
        name: 'Swiss Chocolate Box',
        itemNumber: 'ITM-004',
        barcode: '4567890123456',
        price: 18.50,
        category: 'Food',
        stock: 40,
        image: 'https://placehold.co/400x300/8B4513/FFF?text=Chocolate',
        description: 'Premium Swiss chocolate assortment',
      },
      {
        id: 5,
        name: 'Designer Sunglasses',
        itemNumber: 'ITM-005',
        barcode: '5678901234567',
        price: 149.99,
        category: 'Accessories',
        stock: 0, // Out of stock
        image: 'https://placehold.co/400x300/FFD700/000?text=Sunglasses',
        description: 'UV protection designer sunglasses',
      },
      {
        id: 6,
        name: 'Portable Charger 20000mAh',
        itemNumber: 'ITM-006',
        barcode: '6789012345678',
        price: 45.00,
        category: 'Electronics',
        stock: 25,
        image: 'https://placehold.co/400x300/4169E1/FFF?text=Charger',
        description: 'Fast charging portable power bank',
      },
      {
        id: 7,
        name: 'Cashmere Scarf',
        itemNumber: 'ITM-007',
        barcode: '7890123456789',
        price: 79.99,
        category: 'Accessories',
        stock: 0, // Out of stock
        image: 'https://placehold.co/400x300/DC143C/FFF?text=Scarf',
        description: 'Soft cashmere scarf in various colors',
      },
      {
        id: 8,
        name: 'Travel Size Skincare Set',
        itemNumber: 'ITM-008',
        barcode: '8901234567890',
        price: 34.99,
        category: 'Beauty',
        stock: 22,
        image: 'https://placehold.co/400x300/FF69B4/FFF?text=Skincare',
        description: 'Complete travel skincare routine',
        hasVariants: true,
        variants: [
          {
            size: 'Trial Kit',
            sku: 'SKN-TRIAL',
            barcode: '8901234567890',
            uom: 'SET',
            status: 'Active',
            price: 34.99,
            stock: 22,
          },
          {
            size: 'Deluxe Kit',
            sku: 'SKN-DELUXE',
            barcode: '8901234567891',
            uom: 'SET',
            status: 'Active',
            price: 59.99,
            stock: 12,
          },
          {
            size: 'Premium Kit',
            sku: 'SKN-PREMIUM',
            barcode: '8901234567892',
            uom: 'SET',
            status: 'Active',
            price: 89.99,
            stock: 6,
          },
        ],
      },
      {
        id: 9,
        name: 'Bluetooth Sleep Mask',
        itemNumber: 'ITM-009',
        barcode: '9012345678901',
        price: 39.99,
        category: 'Electronics',
        stock: 20,
        image: 'https://placehold.co/400x300/6A5ACD/FFF?text=Sleep+Mask',
        description: 'Sleep mask with built-in wireless speakers',
      },
      {
        id: 10,
        name: 'Premium Eye Cream',
        itemNumber: 'ITM-010',
        barcode: '0123456789012',
        price: 68.00,
        category: 'Beauty',
        stock: 15,
        image: 'https://placehold.co/400x300/FFB6C1/000?text=Eye+Cream',
        description: 'Anti-aging eye cream with vitamin C',
      },
      {
        id: 11,
        name: 'Leather Passport Holder',
        itemNumber: 'ITM-011',
        barcode: '1122334455667',
        price: 42.50,
        category: 'Accessories',
        stock: 28,
        image: 'https://placehold.co/400x300/8B4513/FFF?text=Passport',
        description: 'Genuine leather passport and card holder',
      },
      {
        id: 12,
        name: 'Noise Cancelling Earbuds',
        itemNumber: 'ITM-012',
        barcode: '2233445566778',
        price: 129.99,
        category: 'Electronics',
        stock: 0, // Out of stock
        image: 'https://placehold.co/400x300/000080/FFF?text=Earbuds',
        description: 'True wireless earbuds with ANC technology',
      },
      {
        id: 13,
        name: 'Artisan Coffee Beans',
        itemNumber: 'ITM-013',
        barcode: '3344556677889',
        price: 22.00,
        category: 'Food',
        stock: 35,
        image: 'https://placehold.co/400x300/654321/FFF?text=Coffee',
        description: 'Single-origin premium roast coffee',
        hasVariants: true,
        variants: [
          {
            size: '250g',
            sku: 'COFFEE-250',
            barcode: '3344556677889',
            uom: 'GRAMS',
            status: 'Active',
            price: 22.00,
            stock: 35,
          },
          {
            size: '500g',
            sku: 'COFFEE-500',
            barcode: '3344556677890',
            uom: 'GRAMS',
            status: 'Active',
            price: 39.99,
            stock: 20,
          },
          {
            size: '1kg',
            sku: 'COFFEE-1000',
            barcode: '3344556677891',
            uom: 'GRAMS',
            status: 'Active',
            price: 69.99,
            stock: 10,
          },
        ],
      },
      {
        id: 14,
        name: 'Silk Sleep Mask',
        itemNumber: 'ITM-014',
        barcode: '4455667788990',
        price: 28.99,
        category: 'Comfort',
        stock: 40,
        image: 'https://placehold.co/400x300/E6E6FA/000?text=Silk+Mask',
        description: 'Pure mulberry silk eye mask',
      },
      {
        id: 15,
        name: 'Designer Watch',
        itemNumber: 'ITM-015',
        barcode: '5566778899001',
        price: 299.00,
        category: 'Accessories',
        stock: 8,
        image: 'https://placehold.co/400x300/C0C0C0/000?text=Watch',
        description: 'Stainless steel automatic watch',
      },
      {
        id: 16,
        name: 'Moisturizing Hand Cream',
        itemNumber: 'ITM-016',
        barcode: '6677889900112',
        price: 16.50,
        category: 'Beauty',
        stock: 50,
        image: 'https://placehold.co/400x300/FFC0CB/000?text=Hand+Cream',
        description: 'Nourishing hand cream with shea butter',
      },
      {
        id: 17,
        name: 'Gourmet Chocolate Truffles',
        itemNumber: 'ITM-017',
        barcode: '7788990011223',
        price: 24.99,
        category: 'Food',
        stock: 32,
        image: 'https://placehold.co/400x300/A0522D/FFF?text=Truffles',
        description: 'Assorted Belgian chocolate truffles',
      },
      {
        id: 18,
        name: 'USB-C Travel Adapter',
        itemNumber: 'ITM-018',
        barcode: '8899001122334',
        price: 32.00,
        category: 'Electronics',
        stock: 45,
        image: 'https://placehold.co/400x300/4682B4/FFF?text=Adapter',
        description: 'Universal travel adapter with USB-C',
      },
      {
        id: 19,
        name: 'Luxury Cologne 100ml',
        itemNumber: 'ITM-019',
        barcode: '9900112233445',
        price: 145.00,
        category: 'Fragrance',
        stock: 14,
        image: 'https://placehold.co/400x300/191970/FFF?text=Cologne',
        description: 'Premium men\'s cologne with woody notes',
      },
      {
        id: 20,
        name: 'Compression Travel Socks',
        itemNumber: 'ITM-020',
        barcode: '0011223344556',
        price: 19.99,
        category: 'Comfort',
        stock: 60,
        image: 'https://placehold.co/400x300/708090/FFF?text=Socks',
        description: 'Medical-grade compression socks',
      },
      {
        id: 21,
        name: 'Wireless Phone Sanitizer',
        itemNumber: 'ITM-021',
        barcode: '1123456789012',
        price: 49.99,
        category: 'Electronics',
        stock: 22,
        image: 'https://placehold.co/400x300/00CED1/000?text=Sanitizer',
        description: 'UV-C phone sanitizer and wireless charger',
      },
      {
        id: 22,
        name: 'Anti-Aging Serum',
        itemNumber: 'ITM-022',
        barcode: '2234567890123',
        price: 85.00,
        category: 'Beauty',
        stock: 18,
        image: 'https://placehold.co/400x300/FF1493/FFF?text=Serum',
        description: 'Hyaluronic acid anti-aging serum',
      },
      {
        id: 23,
        name: 'Smart Luggage Tag',
        itemNumber: 'ITM-023',
        barcode: '3345678901234',
        price: 29.99,
        category: 'Accessories',
        stock: 35,
        image: 'https://placehold.co/400x300/FF8C00/000?text=Tag',
        description: 'Bluetooth-enabled smart luggage tracker',
      },
      {
        id: 24,
        name: 'Organic Green Tea Set',
        itemNumber: 'ITM-024',
        barcode: '4456789012345',
        price: 26.50,
        category: 'Food',
        stock: 28,
        image: 'https://placehold.co/400x300/9ACD32/000?text=Tea',
        description: 'Premium Japanese green tea collection',
      },
      {
        id: 25,
        name: 'Memory Foam Neck Pillow',
        itemNumber: 'ITM-025',
        barcode: '5567890123456',
        price: 35.99,
        category: 'Comfort',
        stock: 38,
        image: 'https://placehold.co/400x300/4169E1/FFF?text=Neck+Pillow',
        description: 'Ergonomic memory foam neck support',
      },
      {
        id: 26,
        name: 'Smart Fitness Band',
        itemNumber: 'ITM-026',
        barcode: '6678901234567',
        price: 79.99,
        category: 'Electronics',
        stock: 16,
        image: 'https://placehold.co/400x300/32CD32/000?text=Fitness',
        description: 'Waterproof fitness tracker with heart monitor',
      },
      {
        id: 27,
        name: 'Designer Lipstick Set',
        itemNumber: 'ITM-027',
        barcode: '7789012345678',
        price: 52.00,
        category: 'Beauty',
        stock: 24,
        image: 'https://placehold.co/400x300/DC143C/FFF?text=Lipstick',
        description: 'Luxury lipstick collection - 5 shades',
      },
      {
        id: 28,
        name: 'Leather Card Wallet',
        itemNumber: 'ITM-028',
        barcode: '8890123456789',
        price: 38.99,
        category: 'Accessories',
        stock: 30,
        image: 'https://placehold.co/400x300/2F4F4F/FFF?text=Wallet',
        description: 'Slim RFID-blocking card holder',
      },
      {
        id: 29,
        name: 'Champagne Chocolates',
        itemNumber: 'ITM-029',
        barcode: '9901234567890',
        price: 31.50,
        category: 'Food',
        stock: 26,
        image: 'https://placehold.co/400x300/DAA520/000?text=Champagne',
        description: 'Dark chocolate with champagne filling',
      },
      {
        id: 30,
        name: 'Portable Espresso Maker',
        itemNumber: 'ITM-030',
        barcode: '0012345678901',
        price: 59.99,
        category: 'Electronics',
        stock: 12,
        image: 'https://placehold.co/400x300/8B0000/FFF?text=Espresso',
        description: 'Manual portable espresso machine',
      },
    ],

    // Flight and trolley information
    flightInfo: {
      flightNumber: 'AA1234',
      trolleyNumber: 'T-05',
    },

    // Crew details
    crewDetails: {
      employeeId: 'CR-1234',
      name: 'Sarah Johnson',
      designation: 'Senior Flight Attendant',
    },

    // Cash register starting float
    cashRegister: [
      { currencyCode: 'USD', amount: 500.00 },
      { currencyCode: 'EUR', amount: 300.00 },
      { currencyCode: 'GBP', amount: 200.00 },
      { currencyCode: 'JPY', amount: 50000.00 },
      { currencyCode: 'AED', amount: 1000.00 },
    ],

    // Permitted currencies with exchange rates
    currencies: [
      {
        code: 'USD',
        name: 'US Dollar',
        symbol: '$',
        exchangeRate: 1.0,
        denominations: [
          { value: 100, count: 0, type: 'bill' },
          { value: 50, count: 0, type: 'bill' },
          { value: 20, count: 0, type: 'bill' },
          { value: 10, count: 0, type: 'bill' },
          { value: 5, count: 0, type: 'bill' },
          { value: 1, count: 0, type: 'bill' },
          { value: 0.25, count: 0, type: 'coin' },
          { value: 0.10, count: 0, type: 'coin' },
          { value: 0.05, count: 0, type: 'coin' },
          { value: 0.01, count: 0, type: 'coin' },
        ],
      },
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
        exchangeRate: 1.10,
        denominations: [
          { value: 500, count: 0, type: 'bill' },
          { value: 200, count: 0, type: 'bill' },
          { value: 100, count: 0, type: 'bill' },
          { value: 50, count: 0, type: 'bill' },
          { value: 20, count: 0, type: 'bill' },
          { value: 10, count: 0, type: 'bill' },
          { value: 5, count: 0, type: 'bill' },
          { value: 2, count: 0, type: 'coin' },
          { value: 1, count: 0, type: 'coin' },
          { value: 0.50, count: 0, type: 'coin' },
          { value: 0.20, count: 0, type: 'coin' },
          { value: 0.10, count: 0, type: 'coin' },
          { value: 0.05, count: 0, type: 'coin' },
          { value: 0.02, count: 0, type: 'coin' },
          { value: 0.01, count: 0, type: 'coin' },
        ],
      },
      {
        code: 'GBP',
        name: 'British Pound',
        symbol: '£',
        exchangeRate: 1.27,
        denominations: [
          { value: 50, count: 0, type: 'bill' },
          { value: 20, count: 0, type: 'bill' },
          { value: 10, count: 0, type: 'bill' },
          { value: 5, count: 0, type: 'bill' },
          { value: 2, count: 0, type: 'coin' },
          { value: 1, count: 0, type: 'coin' },
          { value: 0.50, count: 0, type: 'coin' },
          { value: 0.20, count: 0, type: 'coin' },
          { value: 0.10, count: 0, type: 'coin' },
          { value: 0.05, count: 0, type: 'coin' },
          { value: 0.02, count: 0, type: 'coin' },
          { value: 0.01, count: 0, type: 'coin' },
        ],
      },
      {
        code: 'JPY',
        name: 'Japanese Yen',
        symbol: '¥',
        exchangeRate: 0.0067,
        denominations: [
          { value: 10000, count: 0, type: 'bill' },
          { value: 5000, count: 0, type: 'bill' },
          { value: 2000, count: 0, type: 'bill' },
          { value: 1000, count: 0, type: 'bill' },
          { value: 500, count: 0, type: 'coin' },
          { value: 100, count: 0, type: 'coin' },
          { value: 50, count: 0, type: 'coin' },
          { value: 10, count: 0, type: 'coin' },
          { value: 5, count: 0, type: 'coin' },
          { value: 1, count: 0, type: 'coin' },
        ],
      },
      {
        code: 'AED',
        name: 'UAE Dirham',
        symbol: 'د.إ',
        exchangeRate: 0.27,
        denominations: [
          { value: 1000, count: 0, type: 'bill' },
          { value: 500, count: 0, type: 'bill' },
          { value: 200, count: 0, type: 'bill' },
          { value: 100, count: 0, type: 'bill' },
          { value: 50, count: 0, type: 'bill' },
          { value: 20, count: 0, type: 'bill' },
          { value: 10, count: 0, type: 'bill' },
          { value: 5, count: 0, type: 'bill' },
          { value: 1, count: 0, type: 'coin' },
          { value: 0.50, count: 0, type: 'coin' },
          { value: 0.25, count: 0, type: 'coin' },
        ],
      },
    ],

    // Card networks
    cardNetworks: ['VISA', 'MASTERCARD', 'RUPAY', 'AMEX', 'DISCOVER', 'UNIONPAY'],

    // Authorization methods
    authMethods: ['NO_CVM', 'PIN', 'SIGNATURE', 'BIOMETRIC'],

    // Payment methods
    paymentMethods: [
      { value: 'credit-card', title: 'Credit Card', icon: 'tabler-credit-card' },
      { value: 'debit-card', title: 'Debit Card', icon: 'tabler-credit-card' },
      { value: 'cash', title: 'Cash', icon: 'tabler-cash' },
      { value: 'digital-wallet', title: 'Digital Wallet', icon: 'tabler-wallet' },
    ],
  }
})
